# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/api/calculadorabasica/
Accept: application/json

###

GET http://127.0.0.1:8000/api/calculadorabasica/?operando=10&operador=suma&operando2=5
Accept: application/json

###

GET http://127.0.0.1:8000/api/calculadorabasica/?operando=10&operador=resta&operando2=5
Accept: application/json

###

GET http://127.0.0.1:8000/api/calculadorabasica/?operando=10&operador=multiplicacion&operando2=5
Accept: application/json

###

GET http://127.0.0.1:8000/api/calculadorabasica/?operando=10&operador=division&operando2=5
Accept: application/json

###